Vagrant.configure("2") do |config|
  config.vm.define "hydrogen" do |h|
    h.vm.box = "bento/ubuntu-18.04"
    h.vm.hostname = 'hydrogen'
    #h.disksize.size = '50GB'
    #h.vm.box_url = "ubuntu/precise64"

    h.vm.network :private_network, ip: "192.168.56.1"

    h.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 8192]
      v.customize ["modifyvm", :id, "--name", "hydrogen"]
      v.cpus = 8
    end

    config.vm.provision "shell" , path: "provision-script.sh"
  end
end
